pipeline {
    agent any

    environment {
        IMAGE_NAME = "cicd-demo"
    }

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME 01-CI-CD-Pipeline-Project'
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                docker stop cicd-container || true
                docker rm cicd-container || true
                docker run -d -p 5000:5000 --name cicd-container $IMAGE_NAME
                '''
            }
        }
    }
}